require_relative 'history_entry'

module SmartyStreets
    module USEnrichment
        module Property
            module Principal
                class Attributes
                    attr_reader :first_floor_sqft, :second_floor_sqft, :acres, :air_conditioner, :arbor_pergola, :assessed_improvement_percent, :assessed_improvement_value, :assessed_land_value, 
                    :assessed_value, :assessor_last_update, :assessor_taxroll_update, :attic_area, :attic_flag, :balcony, :balcony_area, :basement_sqft, :basement_sqft_finished, 
                    :basement_sqft_unfinished, :bath_house, :bath_house_sqft, :bathrooms_partial, :bathrooms_total, :bedrooms, :block1, :block2, :boat_access, :boat_house, :boat_house_sqft, 
                    :boat_lift, :bonus_room, :breakfast_nook, :breezeway, :building_definition_code, :building_sqft, :cabin, :cabin_sqft, :canopy, :canopy_sqft, :carport, :carport_sqft, :cbsa_code, 
                    :cbsa_name, :cellar, :census_block, :census_block_group, :census_fips_place_code, :census_tract, :central_vacuum, :code_title_company, :combined_statistical_area, :community_rec, 
                    :company_flag, :congressional_district, :construction_type, :contact_city, :contact_crrt, :contact_full_address, :contact_house_number, :contact_mail_info_format, :contact_mail_info_privacy, 
                    :contact_mailing_county, :contact_mailing_fips, :contact_post_direction, :contact_pre_direction, :contact_state, :contact_street_name, :contact_suffix, :contact_unit_designator, :contact_value, 
                    :contact_zip, :contact_zip4, :courtyard, :courtyard_area, :deck, :deck_area, :deed_document_page, :deed_document_book, :deed_document_number, :deed_owner_first_name, :deed_owner_first_name2, 
                    :deed_owner_first_name3, :deed_owner_first_name4, :deed_owner_full_name, :deed_owner_full_name2, :deed_owner_full_name3, :deed_owner_full_name4, :deed_owner_last_name, :deed_owner_last_name2, 
                    :deed_owner_last_name3, :deed_owner_last_name4, :deed_owner_middle_name, :deed_owner_middle_name2, :deed_owner_middle_name3, :deed_owner_middle_name4, :deed_owner_suffix, :deed_owner_suffix2, 
                    :deed_owner_suffix3, :deed_owner_suffix4, :deed_sale_date, :deed_sale_price, :deed_transaction_id, :depth_linear_footage, :disabled_tax_exemption, :document_type_description, :driveway_sqft, :driveway_type, :effective_year_built, 
                    :elevation_feet, :elevator, :equestrian_arena, :escalator, :exercise_room, :exterior_walls, :family_room, :fence, :fence_area, :financial_history, :fips_code, :fire_resistance_code, :fire_sprinklers_flag, :fireplace,
                    :fireplace_number, :first_name, :first_name_2, :first_name_3, :first_name_4, :flooring, :foundation, :game_room, :garage, :garage_sqft, :gazebo, :gazebo_sqft, :golf_course, :grainery, :grainery_sqft, 
                    :great_room, :greenhouse, :greenhouse_sqft, :gross_sqft, :guesthouse, :guesthouse_sqft, :handicap_accessibility, :heat, :heat_fuel_type, :hobby_room, :homeowner_tax_exemption, :instrument_date, 
                    :intercom_system, :interest_rate_type_2, :interior_structure, :kennel, :kennel_sqft, :land_use_code, :land_use_group, :land_use_standard, :last_name, :last_name_2, :last_name_3, :last_name_4, 
                    :latitude, :laundry, :lean_to, :lean_to_sqft, :legal_description, :legal_unit, :lender_address, :lender_address_2, :lender_city, :lender_city_2, :lender_code_2, :lender_first_name, :lender_first_name_2, 
                    :lender_last_name, :lender_last_name_2, :lender_name, :lender_name_2, :lender_seller_carry_back, :lender_seller_carry_back_2, :lender_state, :lender_state_2, :lender_zip, :lender_zip_2, 
                    :lender_zip_extended, :lender_zip_extended_2, :loading_platform, :loading_platform_sqft, :longitude, :lot_1, :lot_2, :lot_3, :lot_sqft, :market_improvement_percent, :market_improvement_value, 
                    :market_land_value, :market_value_year, :match_type, :media_room, :metro_division, :middle_name, :middle_name_2, :middle_name_3, :middle_name_4, :milkhouse, :milkhouse_sqft, :minor_civil_division_code, 
                    :minor_civil_division_name, :mobile_home_hookup, :mortgage_amount, :mortgage_amount_2, :mortgage_due_date, :mortgage_due_date_2, :mortgage_interest_rate, :mortgage_interest_rate_type, :mortgage_lender_code,
                    :mortgage_rate_2, :mortgage_recording_date, :mortgage_recording_date_2, :mortgage_term, :mortgage_term_2, :mortgage_term_type, :mortgage_term_type_2, :mortgage_type, :mortgage_type_2, :msa_code, :msa_name, 
                    :mud_room, :multi_parcel_flag, :name_title_company, :neighborhood_code, :number_of_buildings, :office, :office_sqft, :other_tax_exemption, :outdoor_kitchen_fireplace, :overhead_door, :owner_full_name, 
                    :owner_full_name_2, :owner_full_name_3, :owner_full_name_4, :owner_occupancy_status, :ownership_transfer_date, :ownership_transfer_doc_number, :ownership_transfer_transaction_id, :ownership_type, 
                    :ownership_type_2, :ownership_vesting_relation_code, :parcel_account_number, :parcel_map_book, :parcel_map_page, :parcel_number_alternate, :parcel_number_formatted, :parcel_number_previous, :parcel_number_year_added, 
                    :parcel_number_year_change, :parcel_raw_number, :parcel_shell_record, :parking_spaces, :patio_area, :phase_name, :plumbing_fixtures_count, :pole_struct, :pole_struct_sqft, :pond, :pool, :pool_area, :poolhouse, 
                    :poolhouse_sqft, :porch, :porch_area, :poultry_house, :poultry_house_sqft, :previous_assessed_value, :prior_sale_amount, :prior_sale_date, :property_address_carrier_route_code, :property_address_city, 
                    :property_address_full, :property_address_house_number, :property_address_post_direction, :property_address_pre_direction, :property_address_state, :property_address_street_name, 
                    :property_address_street_suffix, :property_address_unit_designator, :property_address_unit_value, :property_address_zip_4, :property_address_zipcode, :publication_date, 
                    :quarter, :quarter_quarter, :quonset, :quonset_sqft, :range, :recording_date, :roof_cover, :roof_frame, :rooms, :rv_parking, :safe_room, :sale_amount, :sale_date, :sauna, 
                    :section, :security_alarm, :senior_tax_exemption, :sewer_type, :shed, :shed_sqft, :silo, :silo_sqft, :sitting_room, :situs_county, :situs_state, :sound_system, :sports_court, 
                    :sprinklers, :stable, :stable_sqft, :storage_building, :storage_building_sqft, :stories_number, :storm_shelter, :storm_shutter, :structure_style, :study, :subdivision, 
                    :suffix, :suffix_2, :suffix_3, :suffix_4, :sunroom, :tax_assess_year, :tax_billed_amount, :tax_delinquent_year, :tax_fiscal_year, :tax_jurisdiction, :tax_rate_area, :tennis_court, 
                    :topography_code, :total_market_value, :township, :tract_number, :transfer_amount, :trust_description, :unit_count, :upper_floors_sqft, :utility, :utility_building, 
                    :utility_building_sqft, :utility_sqft, :veteran_tax_exemption, :view_description, :water_feature, :water_service_type, :wet_bar, :widow_tax_exemption, :width_linear_footage, 
                    :wine_cellar, :year_built, :zoning
            
                    def initialize(obj)
                        @first_floor_sqft = obj['1st_floor_sqft']
                        @second_floor_sqft = obj['2nd_floor_sqft']
                        @acres = obj['acres']
                        @air_conditioner = obj['air_conditioner']
                        @arbor_pergola = obj['arbor_pergola']
                        @assessed_improvement_percent = obj['assessed_improvement_percent']
                        @assessed_improvement_value = obj['assessed_improvement_value']
                        @assessed_land_value = obj['assessed_land_value']
                        @assessed_value = obj['assessed_value']
                        @assessor_last_update = obj['assessor_last_update']
                        @assessor_taxroll_update = obj['assessor_taxroll_update']
                        @attic_area = obj['attic_area']
                        @attic_flag = obj['attic_flag']
                        @balcony = obj['balcony']
                        @balcony_area = obj['balcony_area']
                        @basement_sqft = obj['basement_sqft']
                        @basement_sqft_finished = obj['basement_sqft_finished']
                        @basement_sqft_unfinished = obj['basement_sqft_unfinished']
                        @bath_house = obj['bath_house']
                        @bath_house_sqft = obj['bath_house_sqft']
                        @bathrooms_partial = obj['bathrooms_partial']
                        @bathrooms_total = obj['bathrooms_total']
                        @bedrooms = obj['bedrooms']
                        @block1 = obj['block1']
                        @block2 = obj['block2']
                        @boat_access = obj['boat_access']
                        @boat_house = obj['boat_house']
                        @boat_house_sqft = obj['boat_house_sqft']
                        @boat_lift = obj['boat_lift']
                        @bonus_room = obj['bonus_room']
                        @breakfast_nook = obj['breakfast_nook']
                        @breezeway = obj['breezeway']
                        @building_definition_code = obj['building_definition_code']
                        @building_sqft = obj['building_sqft']
                        @cabin = obj['cabin']
                        @cabin_sqft = obj['cabin_sqft']
                        @canopy = obj['canopy']
                        @canopy_sqft = obj['canopy_sqft']
                        @carport = obj['carport']
                        @carport_sqft = obj['carport_sqft']
                        @cbsa_code = obj['cbsa_code']
                        @cbsa_name = obj['cbsa_name']
                        @cellar = obj['cellar']
                        @census_block = obj['census_block']
                        @census_block_group = obj['census_block_group']
                        @census_fips_place_code = obj['census_fips_place_code']
                        @census_tract = obj['census_tract']
                        @central_vacuum = obj['central_vacuum']
                        @code_title_company = obj['code_title_company']
                        @combined_statistical_area = obj['combined_statistical_area']
                        @community_rec = obj['community_rec']
                        @company_flag = obj['company_flag']
                        @congressional_district = obj['congressional_district']
                        @construction_type = obj['construction_type']
                        @contact_city = obj['contact_city']
                        @contact_crrt = obj['contact_crrt']
                        @contact_full_address = obj['contact_full_address']
                        @contact_house_number = obj['contact_house_number']
                        @contact_mail_info_format = obj['contact_mail_info_format']
                        @contact_mail_info_privacy = obj['contact_mail_info_privacy']
                        @contact_mailing_county = obj['contact_mailing_county']
                        @contact_mailing_fips = obj['contact_mailing_fips']
                        @contact_post_direction = obj['contact_post_direction']
                        @contact_pre_direction = obj['contact_pre_direction']
                        @contact_state = obj['contact_state']
                        @contact_street_name = obj['contact_street_name']
                        @contact_suffix = obj['contact_suffix']
                        @contact_unit_designator = obj['contact_unit_designator']
                        @contact_value = obj['contact_value']
                        @contact_zip = obj['contact_zip']
                        @contact_zip4 = obj['contact_zip4']
                        @courtyard = obj['courtyard']
                        @courtyard_area = obj['courtyard_area']
                        @deck = obj['deck']
                        @deck_area = obj['deck_area']
                        @deed_document_page = obj['deed_document_page']
                        @deed_document_book = obj['deed_document_book']
                        @deed_document_number = obj['deed_document_number']
                        @deed_owner_first_name = obj['deed_owner_first_name']
                        @deed_owner_first_name2 = obj['deed_owner_first_name2']
                        @deed_owner_first_name3 = obj['deed_owner_first_name3']
                        @deed_owner_first_name4 = obj['deed_owner_first_name4']
                        @deed_owner_full_name = obj['deed_owner_full_name']
                        @deed_owner_full_name2 = obj['deed_owner_full_name2']
                        @deed_owner_full_name3 = obj['deed_owner_full_name3']
                        @deed_owner_full_name4 = obj['deed_owner_full_name4']
                        @deed_owner_last_name = obj['deed_owner_last_name']
                        @deed_owner_last_name2 = obj['deed_owner_last_name2']
                        @deed_owner_last_name3 = obj['deed_owner_last_name3']
                        @deed_owner_last_name4 = obj['deed_owner_last_name4']
                        @deed_owner_middle_name = obj['deed_owner_middle_name']
                        @deed_owner_middle_name2 = obj['deed_owner_middle_name2']
                        @deed_owner_middle_name3 = obj['deed_owner_middle_name3']
                        @deed_owner_middle_name4 = obj['deed_owner_middle_name4']
                        @deed_owner_suffix = obj['deed_owner_suffix']
                        @deed_owner_suffix2 = obj['deed_owner_suffix2']
                        @deed_owner_suffix3 = obj['deed_owner_suffix3']
                        @deed_owner_suffix4 = obj['deed_owner_suffix4']
                        @deed_sale_date = obj['deed_sale_date']
                        @deed_sale_price = obj['deed_sale_price']
                        @deed_transaction_id = obj['deed_transaction_id']
                        @depth_linear_footage = obj['depth_linear_footage']
                        @disabled_tax_exemption = obj['disabled_tax_exemption']
                        @document_type_description = obj['document_type_description']
                        @driveway_sqft = obj['driveway_sqft']
                        @driveway_type = obj['driveway_type']
                        @effective_year_built = obj['effective_year_built']
                        @elevation_feet = obj['elevation_feet']
                        @elevator = obj['elevator']
                        @equestrian_arena = obj['equestrian_arena']
                        @escalator = obj['escalator']
                        @exercise_room = obj['exercise_room']
                        @exterior_walls = obj['exterior_walls']
                        @family_room = obj['family_room']
                        @fence = obj['fence']
                        @fence_area = obj['fence_area']
                        @financial_history = createFinancialHistory(obj['financial_history'])
                        @fips_code = obj['fips_code']
                        @fire_resistance_code = obj['fire_resistance_code']
                        @fire_sprinklers_flag = obj['fire_sprinklers_flag']
                        @fireplace = obj['fireplace']
                        @fireplace_number = obj['fireplace_number']
                        @first_name = obj['first_name']
                        @first_name_2 = obj['first_name_2']
                        @first_name_3 = obj['first_name_3']
                        @first_name_4 = obj['first_name_4']
                        @flooring = obj['flooring']
                        @foundation = obj['foundation']
                        @game_room = obj['game_room']
                        @garage = obj['garage']
                        @garage_sqft = obj['garage_sqft']
                        @gazebo = obj['gazebo']
                        @gazebo_sqft = obj['gazebo_sqft']
                        @golf_course = obj['golf_course']
                        @grainery = obj['grainery']
                        @grainery_sqft = obj['grainery_sqft']
                        @great_room = obj['great_room']
                        @greenhouse = obj['greenhouse']
                        @greenhouse_sqft = obj['greenhouse_sqft']
                        @gross_sqft = obj['gross_sqft']
                        @guesthouse = obj['guesthouse']
                        @guesthouse_sqft = obj['guesthouse_sqft']
                        @handicap_accessibility = obj['handicap_accessibility']
                        @heat = obj['heat']
                        @heat_fuel_type = obj['heat_fuel_type']
                        @hobby_room = obj['hobby_room']
                        @homeowner_tax_exemption = obj['homeowner_tax_exemption']
                        @instrument_date = obj['instrument_date']
                        @intercom_system = obj['intercom_system']
                        @interest_rate_type_2 = obj['interest_rate_type_2']
                        @interior_structure = obj['interior_structure']
                        @kennel = obj['kennel']
                        @kennel_sqft = obj['kennel_sqft']
                        @land_use_code = obj['land_use_code']
                        @land_use_group = obj['land_use_group']
                        @land_use_standard = obj['land_use_standard']
                        @last_name = obj['last_name']
                        @last_name_2 = obj['last_name_2']
                        @last_name_3 = obj['last_name_3']
                        @last_name_4 = obj['last_name_4']
                        @latitude = obj['latitude']
                        @laundry = obj['laundry']
                        @lean_to = obj['lean_to']
                        @lean_to_sqft = obj['lean_to_sqft']
                        @legal_description = obj['legal_description']
                        @legal_unit = obj['legal_unit']
                        @lender_address = obj['lender_address']
                        @lender_address_2 = obj['lender_address_2']
                        @lender_city = obj['lender_city']
                        @lender_city_2 = obj['lender_city_2']
                        @lender_code_2 = obj['lender_code_2']
                        @lender_first_name = obj['lender_first_name']
                        @lender_first_name_2 = obj['lender_first_name_2']
                        @lender_last_name = obj['lender_last_name']
                        @lender_last_name_2 = obj['lender_last_name_2']
                        @lender_name = obj['lender_name']
                        @lender_name_2 = obj['lender_name_2']
                        @lender_seller_carry_back = obj['lender_seller_carry_back']
                        @lender_seller_carry_back_2 = obj['lender_seller_carry_back_2']
                        @lender_state = obj['lender_state']
                        @lender_state_2 = obj['lender_state_2']
                        @lender_zip = obj['lender_zip']
                        @lender_zip_2 = obj['lender_zip_2']
                        @lender_zip_extended = obj['lender_zip_extended']
                        @lender_zip_extended_2 = obj['lender_zip_extended_2']
                        @loading_platform = obj['loading_platform']
                        @loading_platform_sqft = obj['loading_platform_sqft']
                        @longitude = obj['longitude']
                        @lot_1 = obj['lot_1']
                        @lot_2 = obj['lot_2']
                        @lot_3 = obj['lot_3']
                        @lot_sqft = obj['lot_sqft']
                        @market_improvement_percent = obj['market_improvement_percent']
                        @market_improvement_value = obj['market_improvement_value']
                        @market_land_value = obj['market_land_value']
                        @market_value_year = obj['market_value_year']
                        @match_type = obj['match_type']
                        @media_room = obj['media_room']
                        @metro_division = obj['metro_division']
                        @middle_name = obj['middle_name']
                        @middle_name_2 = obj['middle_name_2']
                        @middle_name_3 = obj['middle_name_3']
                        @middle_name_4 = obj['middle_name_4']
                        @milkhouse = obj['milkhouse']
                        @milkhouse_sqft = obj['milkhouse_sqft']
                        @minor_civil_division_code = obj['minor_civil_division_code']
                        @minor_civil_division_name = obj['minor_civil_division_name']
                        @mobile_home_hookup = obj['mobile_home_hookup']
                        @mortgage_amount = obj['mortgage_amount']
                        @mortgage_amount_2 = obj['mortgage_amount_2']
                        @mortgage_due_date = obj['mortgage_due_date']
                        @mortgage_due_date_2 = obj['mortgage_due_date_2']
                        @mortgage_interest_rate = obj['mortgage_interest_rate']
                        @mortgage_interest_rate_type = obj['mortgage_interest_rate_type']
                        @mortgage_lender_code = obj['mortgage_lender_code']
                        @mortgage_rate_2 = obj['mortgage_rate_2']
                        @mortgage_recording_date = obj['mortgage_recording_date']
                        @mortgage_recording_date_2 = obj['mortgage_recording_date_2']
                        @mortgage_term = obj['mortgage_term']
                        @mortgage_term_2 = obj['mortgage_term_2']
                        @mortgage_term_type = obj['mortgage_term_type']
                        @mortgage_term_type_2 = obj['mortgage_term_type_2']
                        @mortgage_type = obj['mortgage_type']
                        @mortgage_type_2 = obj['mortgage_type_2']
                        @msa_code = obj['msa_code']
                        @msa_name = obj['msa_name']
                        @mud_room = obj['mud_room']
                        @multi_parcel_flag = obj['multi_parcel_flag']
                        @name_title_company = obj['name_title_company']
                        @neighborhood_code = obj['neighborhood_code']
                        @number_of_buildings = obj['number_of_buildings']
                        @office = obj['office']
                        @office_sqft = obj['office_sqft']
                        @other_tax_exemption = obj['other_tax_exemption']
                        @outdoor_kitchen_fireplace = obj['outdoor_kitchen_fireplace']
                        @overhead_door = obj['overhead_door']
                        @owner_full_name = obj['owner_full_name']
                        @owner_full_name_2 = obj['owner_full_name_2']
                        @owner_full_name_3 = obj['owner_full_name_3']
                        @owner_full_name_4 = obj['owner_full_name_4']
                        @owner_occupancy_status = obj['owner_occupancy_status']
                        @ownership_transfer_date = obj['ownership_transfer_date']
                        @ownership_transfer_doc_number = obj['ownership_transfer_doc_number']
                        @ownership_transfer_transaction_id = obj['ownership_transfer_transaction_id']
                        @ownership_type = obj['ownership_type']
                        @ownership_type_2 = obj['ownership_type_2']
                        @ownership_vesting_relation_code = obj['ownership_vesting_relation_code']
                        @parcel_account_number = obj['parcel_account_number']
                        @parcel_map_book = obj['parcel_map_book']
                        @parcel_map_page = obj['parcel_map_page']
                        @parcel_number_alternate = obj['parcel_number_alternate']
                        @parcel_number_formatted = obj['parcel_number_formatted']
                        @parcel_number_previous = obj['parcel_number_previous']
                        @parcel_number_year_added = obj['parcel_number_year_added']
                        @parcel_number_year_change = obj['parcel_number_year_change']
                        @parcel_raw_number = obj['parcel_raw_number']
                        @parcel_shell_record = obj['parcel_shell_record']
                        @parking_spaces = obj['parking_spaces']
                        @patio_area = obj['patio_area']
                        @phase_name = obj['phase_name']
                        @plumbing_fixtures_count = obj['plumbing_fixtures_count']
                        @pole_struct = obj['pole_struct']
                        @pole_struct_sqft = obj['pole_struct_sqft']
                        @pond = obj['pond']
                        @pool = obj['pool']
                        @pool_area = obj['pool_area']
                        @poolhouse = obj['poolhouse']
                        @poolhouse_sqft = obj['poolhouse_sqft']
                        @porch = obj['porch']
                        @porch_area = obj['porch_area']
                        @poultry_house = obj['poultry_house']
                        @poultry_house_sqft = obj['poultry_house_sqft']
                        @previous_assessed_value = obj['previous_assessed_value']
                        @prior_sale_amount = obj['prior_sale_amount']
                        @prior_sale_date = obj['prior_sale_date']
                        @property_address_carrier_route_code = obj['property_address_carrier_route_code']
                        @property_address_city = obj['property_address_city']
                        @property_address_full = obj['property_address_full']
                        @property_address_house_number = obj['property_address_house_number']
                        @property_address_post_direction = obj['property_address_post_direction']
                        @property_address_pre_direction = obj['property_address_pre_direction']
                        @property_address_state = obj['property_address_state']
                        @property_address_street_name = obj['property_address_street_name']
                        @property_address_street_suffix = obj['property_address_street_suffix']
                        @property_address_unit_designator = obj['property_address_unit_designator']
                        @property_address_unit_value = obj['property_address_unit_value']
                        @property_address_zip_4 = obj['property_address_zip_4']
                        @property_address_zipcode = obj['property_address_zipcode']
                        @publication_date = obj['publication_date']
                        @quarter = obj['quarter']
                        @quarter_quarter = obj['quarter_quarter']
                        @quonset = obj['quonset']
                        @quonset_sqft = obj['quonset_sqft']
                        @range = obj['range']
                        @recording_date = obj['recording_date']
                        @roof_cover = obj['roof_cover']
                        @roof_frame = obj['roof_frame']
                        @rooms = obj['rooms']
                        @rv_parking = obj['rv_parking']
                        @safe_room = obj['safe_room']
                        @sale_amount = obj['sale_amount']
                        @sale_date = obj['sale_date']
                        @sauna = obj['sauna']
                        @section = obj['section']
                        @security_alarm = obj['security_alarm']
                        @senior_tax_exemption = obj['senior_tax_exemption']
                        @sewer_type = obj['sewer_type']
                        @shed = obj['shed']
                        @shed_sqft = obj['shed_sqft']
                        @silo = obj['silo']
                        @silo_sqft = obj['silo_sqft']
                        @sitting_room = obj['sitting_room']
                        @situs_county = obj['situs_county']
                        @situs_state = obj['situs_state']
                        @sound_system = obj['sound_system']
                        @sports_court = obj['sports_court']
                        @sprinklers = obj['sprinklers']
                        @stable = obj['stable']
                        @stable_sqft = obj['stable_sqft']
                        @storage_building = obj['storage_building']
                        @storage_building_sqft = obj['storage_building_sqft']
                        @stories_number = obj['stories_number']
                        @storm_shelter = obj['storm_shelter']
                        @storm_shutter = obj['storm_shutter']
                        @structure_style = obj['structure_style']
                        @study = obj['study']
                        @subdivision = obj['subdivision']
                        @suffix = obj['suffix']
                        @suffix_2 = obj['suffix_2']
                        @suffix_3 = obj['suffix_3']
                        @suffix_4 = obj['suffix_4']
                        @sunroom = obj['sunroom']
                        @tax_assess_year = obj['tax_assess_year']
                        @tax_billed_amount = obj['tax_billed_amount']
                        @tax_delinquent_year = obj['tax_delinquent_year']
                        @tax_fiscal_year = obj['tax_fiscal_year']
                        @tax_jurisdiction = obj['tax_jurisdiction']
                        @tax_rate_area = obj['tax_rate_area']
                        @tennis_court = obj['tennis_court']
                        @topography_code = obj['topography_code']
                        @total_market_value = obj['total_market_value']
                        @township = obj['township']
                        @tract_number = obj['tract_number']
                        @transfer_amount = obj['transfer_amount']
                        @trust_description = obj['trust_description']
                        @unit_count = obj['unit_count']
                        @upper_floors_sqft = obj['upper_floors_sqft']
                        @utility = obj['utility']
                        @utility_building = obj['utility_building']
                        @utility_building_sqft = obj['utility_building_sqft']
                        @utility_sqft = obj['utility_sqft']
                        @veteran_tax_exemption = obj['veteran_tax_exemption']
                        @view_description = obj['view_description']
                        @water_feature = obj['water_feature']
                        @water_service_type = obj['water_service_type']
                        @wet_bar = obj['wet_bar']
                        @widow_tax_exemption = obj['widow_tax_exemption']
                        @width_linear_footage = obj['width_linear_footage']
                        @wine_cellar = obj['wine_cellar']
                        @year_built = obj['year_built']
                        @zoning = obj['zoning']
                    end

                    def createFinancialHistory(historyArray)
                        entryArray = []
                        if historyArray.nil?
                            return []
                        end
                        for entry in historyArray do
                            entryArray << Principal::HistoryEntry.new(entry)
                        end
                        return entryArray
                    end
                end
            end
        end
    end
end