module SmartyStreets
    module USEnrichment
        module Risk
            class Attributes
                attr_reader :AGRIVALUE, :ALR_NPCTL, :ALR_VALA, :ALR_VALB, :ALR_VALP, :ALR_VRA_NPCTL, :AREA, :AVLN_AFREQ, :AVLN_ALRB, :AVLN_ALRP,
                :AVLN_ALR_NPCTL, :AVLN_EALB, :AVLN_EALP, :AVLN_EALPE, :AVLN_EALR, :AVLN_EALS, :AVLN_EALT, :AVLN_EVNTS, :AVLN_EXPB, :AVLN_EXPP,
                :AVLN_EXPPE, :AVLN_EXPT, :AVLN_EXP_AREA, :AVLN_HLRB, :AVLN_HLRP, :AVLN_HLRR, :AVLN_RISKR, :AVLN_RISKS, :AVLN_RISKV, :BUILDVALUE,
                :CFLD_AFREQ, :CFLD_ALRB, :CFLD_ALRP, :CFLD_ALR_NPCTL, :CFLD_EALB, :CFLD_EALP, :CFLD_EALPE, :CFLD_EALR, :CFLD_EALS, :CFLD_EALT,
                :CFLD_EVNTS, :CFLD_EXPB, :CFLD_EXPP, :CFLD_EXPPE, :CFLD_EXPT, :CFLD_EXP_AREA, :CFLD_HLRB, :CFLD_HLRP, :CFLD_HLRR, :CFLD_RISKR,
                :CFLD_RISKS, :CFLD_RISKV, :COUNTY, :COUNTYFIPS, :COUNTYTYPE, :CRF_VALUE, :CWAV_AFREQ, :CWAV_ALRA, :CWAV_ALRB, :CWAV_ALRP,
                :CWAV_ALR_NPCTL, :CWAV_EALA, :CWAV_EALB, :CWAV_EALP, :CWAV_EALPE, :CWAV_EALR, :CWAV_EALS, :CWAV_EALT, :CWAV_EVNTS, :CWAV_EXPA,
                :CWAV_EXPB, :CWAV_EXPP, :CWAV_EXPPE, :CWAV_EXPT, :CWAV_EXP_AREA, :CWAV_HLRA, :CWAV_HLRB, :CWAV_HLRP, :CWAV_HLRR, :CWAV_RISKR,
                :CWAV_RISKS, :CWAV_RISKV, :DRGT_AFREQ, :DRGT_ALRA, :DRGT_ALR_NPCTL, :DRGT_EALA, :DRGT_EALR, :DRGT_EALS, :DRGT_EALT, :DRGT_EVNTS,
                :DRGT_EXPA, :DRGT_EXPT, :DRGT_EXP_AREA, :DRGT_HLRA, :DRGT_HLRR, :DRGT_RISKR, :DRGT_RISKS, :DRGT_RISKV, :EAL_RATNG, :EAL_SCORE,
                :EAL_SPCTL, :EAL_VALA, :EAL_VALB, :EAL_VALP, :EAL_VALPE, :EAL_VALT, :ERQK_AFREQ, :ERQK_ALRB, :ERQK_ALRP, :ERQK_ALR_NPCTL, :ERQK_EALB,
                :ERQK_EALP, :ERQK_EALPE, :ERQK_EALR, :ERQK_EALS, :ERQK_EALT, :ERQK_EVNTS, :ERQK_EXPB, :ERQK_EXPP, :ERQK_EXPPE, :ERQK_EXPT,
                :ERQK_EXP_AREA, :ERQK_HLRB, :ERQK_HLRP, :ERQK_HLRR, :ERQK_RISKR, :ERQK_RISKS, :ERQK_RISKV, :HAIL_AFREQ, :HAIL_ALRA, :HAIL_ALRB,
                :HAIL_ALRP, :HAIL_ALR_NPCTL, :HAIL_EALA, :HAIL_EALB, :HAIL_EALP, :HAIL_EALPE, :HAIL_EALR, :HAIL_EALS, :HAIL_EALT, :HAIL_EVNTS,
                :HAIL_EXPA, :HAIL_EXPB, :HAIL_EXPP, :HAIL_EXPPE, :HAIL_EXPT, :HAIL_EXP_AREA, :HAIL_HLRA, :HAIL_HLRB, :HAIL_HLRP, :HAIL_HLRR,
                :HAIL_RISKR, :HAIL_RISKS, :HAIL_RISKV, :HRCN_AFREQ, :HRCN_ALRA, :HRCN_ALRB, :HRCN_ALRP, :HRCN_ALR_NPCTL, :HRCN_EALA, :HRCN_EALB,
                :HRCN_EALP, :HRCN_EALPE, :HRCN_EALR, :HRCN_EALS, :HRCN_EALT, :HRCN_EVNTS, :HRCN_EXPA, :HRCN_EXPB, :HRCN_EXPP, :HRCN_EXPPE,
                :HRCN_EXPT, :HRCN_EXP_AREA, :HRCN_HLRA, :HRCN_HLRB, :HRCN_HLRP, :HRCN_HLRR, :HRCN_RISKR, :HRCN_RISKS, :HRCN_RISKV, :HWAV_AFREQ,
                :HWAV_ALRA, :HWAV_ALRB, :HWAV_ALRP, :HWAV_ALR_NPCTL, :HWAV_EALA, :HWAV_EALB, :HWAV_EALP, :HWAV_EALPE, :HWAV_EALR, :HWAV_EALS,
                :HWAV_EALT, :HWAV_EVNTS, :HWAV_EXPA, :HWAV_EXPB, :HWAV_EXPP, :HWAV_EXPPE, :HWAV_EXPT, :HWAV_EXP_AREA, :HWAV_HLRA, :HWAV_HLRB,
                :HWAV_HLRP, :HWAV_HLRR, :HWAV_RISKR, :HWAV_RISKS, :HWAV_RISKV, :ISTM_AFREQ, :ISTM_ALRB, :ISTM_ALRP, :ISTM_ALR_NPCTL, :ISTM_EALB,
                :ISTM_EALP, :ISTM_EALPE, :ISTM_EALR, :ISTM_EALS, :ISTM_EALT, :ISTM_EVNTS, :ISTM_EXPB, :ISTM_EXPP, :ISTM_EXPPE, :ISTM_EXPT,
                :ISTM_EXP_AREA, :ISTM_HLRB, :ISTM_HLRP, :ISTM_HLRR, :ISTM_RISKR, :ISTM_RISKS, :ISTM_RISKV, :LNDS_AFREQ, :LNDS_ALRB, :LNDS_ALRP,
                :LNDS_ALR_NPCTL, :LNDS_EALB, :LNDS_EALP, :LNDS_EALPE, :LNDS_EALR, :LNDS_EALS, :LNDS_EALT, :LNDS_EVNTS, :LNDS_EXPB, :LNDS_EXPP,
                :LNDS_EXPPE, :LNDS_EXPT, :LNDS_EXP_AREA, :LNDS_HLRB, :LNDS_HLRP, :LNDS_HLRR, :LNDS_RISKR, :LNDS_RISKS, :LNDS_RISKV, :LTNG_AFREQ,
                :LTNG_ALRB, :LTNG_ALRP, :LTNG_ALR_NPCTL, :LTNG_EALB, :LTNG_EALP, :LTNG_EALPE, :LTNG_EALR, :LTNG_EALS, :LTNG_EALT, :LTNG_EVNTS,
                :LTNG_EXPB, :LTNG_EXPP, :LTNG_EXPPE, :LTNG_EXPT, :LTNG_EXP_AREA, :LTNG_HLRB, :LTNG_HLRP, :LTNG_HLRR, :LTNG_RISKR, :LTNG_RISKS,
                :LTNG_RISKV, :NRI_VER, :POPULATION, :RESL_RATNG, :RESL_SCORE, :RESL_SPCTL, :RESL_VALUE, :RFLD_AFREQ, :RFLD_ALRA, :RFLD_ALRB,
                :RFLD_ALRP, :RFLD_ALR_NPCTL, :RFLD_EALA, :RFLD_EALB, :RFLD_EALP, :RFLD_EALPE, :RFLD_EALR, :RFLD_EALS, :RFLD_EALT, :RFLD_EVNTS,
                :RFLD_EXPA, :RFLD_EXPB, :RFLD_EXPP, :RFLD_EXPPE, :RFLD_EXPT, :RFLD_EXP_AREA, :RFLD_HLRA, :RFLD_HLRB, :RFLD_HLRP, :RFLD_HLRR,
                :RFLD_RISKR, :RFLD_RISKS, :RFLD_RISKV, :RISK_RATNG, :RISK_SCORE, :RISK_SPCTL, :RISK_VALUE, :SOVI_RATNG, :SOVI_SCORE,
                :SOVI_SPCTL, :STATE, :STATEABBRV, :STATEFIPS, :STCOFIPS, :SWND_AFREQ, :SWND_ALRA, :SWND_ALRB, :SWND_ALRP, :SWND_ALR_NPCTL,
                :SWND_EALA, :SWND_EALB, :SWND_EALP, :SWND_EALPE, :SWND_EALR, :SWND_EALS, :SWND_EALT, :SWND_EVNTS, :SWND_EXPA, :SWND_EXPB,
                :SWND_EXPP, :SWND_EXPPE, :SWND_EXPT, :SWND_EXP_AREA, :SWND_HLRA, :SWND_HLRB, :SWND_HLRP, :SWND_HLRR, :SWND_RISKR, :SWND_RISKS,
                :SWND_RISKV, :TRACT, :TRACTFIPS, :TRND_AFREQ, :TRND_ALRA, :TRND_ALRB, :TRND_ALRP, :TRND_ALR_NPCTL, :TRND_EALA, :TRND_EALB,
                :TRND_EALP, :TRND_EALPE, :TRND_EALR, :TRND_EALS, :TRND_EALT, :TRND_EVNTS, :TRND_EXPA, :TRND_EXPB, :TRND_EXPP, :TRND_EXPPE,
                :TRND_EXPT, :TRND_EXP_AREA, :TRND_HLRA, :TRND_HLRB, :TRND_HLRP, :TRND_HLRR, :TRND_RISKR, :TRND_RISKS, :TRND_RISKV, :TSUN_AFREQ,
                :TSUN_ALRB, :TSUN_ALRP, :TSUN_ALR_NPCTL, :TSUN_EALB, :TSUN_EALP, :TSUN_EALPE, :TSUN_EALR, :TSUN_EALS, :TSUN_EALT, :TSUN_EVNTS,
                :TSUN_EXPB, :TSUN_EXPP, :TSUN_EXPPE, :TSUN_EXPT, :TSUN_EXP_AREA, :TSUN_HLRB, :TSUN_HLRP, :TSUN_HLRR, :TSUN_RISKR, :TSUN_RISKS,
                :TSUN_RISKV, :VLCN_AFREQ, :VLCN_ALRB, :VLCN_ALRP, :VLCN_ALR_NPCTL, :VLCN_EALB, :VLCN_EALP, :VLCN_EALPE, :VLCN_EALR,
                :VLCN_EALS, :VLCN_EALT, :VLCN_EVNTS, :VLCN_EXPB, :VLCN_EXPP, :VLCN_EXPPE, :VLCN_EXPT, :VLCN_EXP_AREA, :VLCN_HLRB,
                :VLCN_HLRP, :VLCN_HLRR, :VLCN_RISKR, :VLCN_RISKS, :VLCN_RISKV, :WFIR_AFREQ, :WFIR_ALRA, :WFIR_ALRB, :WFIR_ALRP,
                :WFIR_ALR_NPCTL, :WFIR_EALA, :WFIR_EALB, :WFIR_EALP, :WFIR_EALPE, :WFIR_EALR, :WFIR_EALS, :WFIR_EALT, :WFIR_EVNTS,
                :WFIR_EXPA, :WFIR_EXPB, :WFIR_EXPP, :WFIR_EXPPE, :WFIR_EXPT, :WFIR_EXP_AREA, :WFIR_HLRA, :WFIR_HLRB, :WFIR_HLRP,
                :WFIR_HLRR, :WFIR_RISKR, :WFIR_RISKS, :WFIR_RISKV, :WNTW_AFREQ, :WNTW_ALRA, :WNTW_ALRB, :WNTW_ALRP, :WNTW_ALR_NPCTL,
                :WNTW_EALA, :WNTW_EALB, :WNTW_EALP, :WNTW_EALPE, :WNTW_EALR, :WNTW_EALS, :WNTW_EALT, :WNTW_EVNTS, :WNTW_EXPA,
                :WNTW_EXPB, :WNTW_EXPP, :WNTW_EXPPE, :WNTW_EXPT, :WNTW_EXP_AREA, :WNTW_HLRA, :WNTW_HLRB, :WNTW_HLRP, :WNTW_HLRR,
                :WNTW_RISKR, :WNTW_RISKS, :WNTW_RISKV

                def initialize(obj)
                    @AGRIVALUE = obj['AGRIVALUE']
                    @ALR_NPCTL = obj['ALR_NPCTL']
                    @ALR_VALA = obj['ALR_VALA']
                    @ALR_VALB = obj['ALR_VALB']
                    @ALR_VALP = obj['ALR_VALP']
                    @ALR_VRA_NPCTL = obj['ALR_VRA_NPCTL']
                    @AREA = obj['AREA']
                    @AVLN_AFREQ = obj['AVLN_AFREQ']
                    @AVLN_ALRB = obj['AVLN_ALRB']
                    @AVLN_ALRP = obj['AVLN_ALRP']
                    @AVLN_ALR_NPCTL = obj['AVLN_ALR_NPCTL']
                    @AVLN_EALB = obj['AVLN_EALB']
                    @AVLN_EALP = obj['AVLN_EALP']
                    @AVLN_EALPE = obj['AVLN_EALPE']
                    @AVLN_EALR = obj['AVLN_EALR']
                    @AVLN_EALS = obj['AVLN_EALS']
                    @AVLN_EALT = obj['AVLN_EALT']
                    @AVLN_EVNTS = obj['AVLN_EVNTS']
                    @AVLN_EXPB = obj['AVLN_EXPB']
                    @AVLN_EXPP = obj['AVLN_EXPP']
                    @AVLN_EXPPE = obj['AVLN_EXPPE']
                    @AVLN_EXPT = obj['AVLN_EXPT']
                    @AVLN_EXP_AREA = obj['AVLN_EXP_AREA']
                    @AVLN_HLRB = obj['AVLN_HLRB']
                    @AVLN_HLRP = obj['AVLN_HLRP']
                    @AVLN_HLRR = obj['AVLN_HLRR']
                    @AVLN_RISKR = obj['AVLN_RISKR']
                    @AVLN_RISKS = obj['AVLN_RISKS']
                    @AVLN_RISKV = obj['AVLN_RISKV']
                    @BUILDVALUE = obj['BUILDVALUE']
                    @CFLD_AFREQ = obj['CFLD_AFREQ']
                    @CFLD_ALRB = obj['CFLD_ALRB']
                    @CFLD_ALRP = obj['CFLD_ALRP']
                    @CFLD_ALR_NPCTL = obj['CFLD_ALR_NPCTL']
                    @CFLD_EALB = obj['CFLD_EALB']
                    @CFLD_EALP = obj['CFLD_EALP']
                    @CFLD_EALPE = obj['CFLD_EALPE']
                    @CFLD_EALR = obj['CFLD_EALR']
                    @CFLD_EALS = obj['CFLD_EALS']
                    @CFLD_EALT = obj['CFLD_EALT']
                    @CFLD_EVNTS = obj['CFLD_EVNTS']
                    @CFLD_EXPB = obj['CFLD_EXPB']
                    @CFLD_EXPP = obj['CFLD_EXPP']
                    @CFLD_EXPPE = obj['CFLD_EXPPE']
                    @CFLD_EXPT = obj['CFLD_EXPT']
                    @CFLD_EXP_AREA = obj['CFLD_EXP_AREA']
                    @CFLD_HLRB = obj['CFLD_HLRB']
                    @CFLD_HLRP = obj['CFLD_HLRP']
                    @CFLD_HLRR = obj['CFLD_HLRR']
                    @CFLD_RISKR = obj['CFLD_RISKR']
                    @CFLD_RISKS = obj['CFLD_RISKS']
                    @CFLD_RISKV = obj['CFLD_RISKV']
                    @COUNTY = obj['COUNTY']
                    @COUNTYFIPS = obj['COUNTYFIPS']
                    @COUNTYTYPE = obj['COUNTYTYPE']
                    @CRF_VALUE = obj['CRF_VALUE']
                    @CWAV_AFREQ = obj['CWAV_AFREQ']
                    @CWAV_ALRA = obj['CWAV_ALRA']
                    @CWAV_ALRB = obj['CWAV_ALRB']
                    @CWAV_ALRP = obj['CWAV_ALRP']
                    @CWAV_ALR_NPCTL = obj['CWAV_ALR_NPCTL']
                    @CWAV_EALA = obj['CWAV_EALA']
                    @CWAV_EALB = obj['CWAV_EALB']
                    @CWAV_EALP = obj['CWAV_EALP']
                    @CWAV_EALPE = obj['CWAV_EALPE']
                    @CWAV_EALR = obj['CWAV_EALR']
                    @CWAV_EALS = obj['CWAV_EALS']
                    @CWAV_EALT = obj['CWAV_EALT']
                    @CWAV_EVNTS = obj['CWAV_EVNTS']
                    @CWAV_EXPA = obj['CWAV_EXPA']
                    @CWAV_EXPB = obj['CWAV_EXPB']
                    @CWAV_EXPP = obj['CWAV_EXPP']
                    @CWAV_EXPPE = obj['CWAV_EXPPE']
                    @CWAV_EXPT = obj['CWAV_EXPT']
                    @CWAV_EXP_AREA = obj['CWAV_EXP_AREA']
                    @CWAV_HLRA = obj['CWAV_HLRA']
                    @CWAV_HLRB = obj['CWAV_HLRB']
                    @CWAV_HLRP = obj['CWAV_HLRP']
                    @CWAV_HLRR = obj['CWAV_HLRR']
                    @CWAV_RISKR = obj['CWAV_RISKR']
                    @CWAV_RISKS = obj['CWAV_RISKS']
                    @CWAV_RISKV = obj['CWAV_RISKV']
                    @DRGT_AFREQ = obj['DRGT_AFREQ']
                    @DRGT_ALRA = obj['DRGT_ALRA']
                    @DRGT_ALR_NPCTL = obj['DRGT_ALR_NPCTL']
                    @DRGT_EALA = obj['DRGT_EALA']
                    @DRGT_EALR = obj['DRGT_EALR']
                    @DRGT_EALS = obj['DRGT_EALS']
                    @DRGT_EALT = obj['DRGT_EALT']
                    @DRGT_EVNTS = obj['DRGT_EVNTS']
                    @DRGT_EXPA = obj['DRGT_EXPA']
                    @DRGT_EXPT = obj['DRGT_EXPT']
                    @DRGT_EXP_AREA = obj['DRGT_EXP_AREA']
                    @DRGT_HLRA = obj['DRGT_HLRA']
                    @DRGT_HLRR = obj['DRGT_HLRR']
                    @DRGT_RISKR = obj['DRGT_RISKR']
                    @DRGT_RISKS = obj['DRGT_RISKS']
                    @DRGT_RISKV = obj['DRGT_RISKV']
                    @EAL_RATNG = obj['EAL_RATNG']
                    @EAL_SCORE = obj['EAL_SCORE']
                    @EAL_SPCTL = obj['EAL_SPCTL']
                    @EAL_VALA = obj['EAL_VALA']
                    @EAL_VALB = obj['EAL_VALB']
                    @EAL_VALP = obj['EAL_VALP']
                    @EAL_VALPE = obj['EAL_VALPE']
                    @EAL_VALT = obj['EAL_VALT']
                    @ERQK_AFREQ = obj['ERQK_AFREQ']
                    @ERQK_ALRB = obj['ERQK_ALRB']
                    @ERQK_ALRP = obj['ERQK_ALRP']
                    @ERQK_ALR_NPCTL = obj['ERQK_ALR_NPCTL']
                    @ERQK_EALB = obj['ERQK_EALB']
                    @ERQK_EALP = obj['ERQK_EALP']
                    @ERQK_EALPE = obj['ERQK_EALPE']
                    @ERQK_EALR = obj['ERQK_EALR']
                    @ERQK_EALS = obj['ERQK_EALS']
                    @ERQK_EALT = obj['ERQK_EALT']
                    @ERQK_EVNTS = obj['ERQK_EVNTS']
                    @ERQK_EXPB = obj['ERQK_EXPB']
                    @ERQK_EXPP = obj['ERQK_EXPP']
                    @ERQK_EXPPE = obj['ERQK_EXPPE']
                    @ERQK_EXPT = obj['ERQK_EXPT']
                    @ERQK_EXP_AREA = obj['ERQK_EXP_AREA']
                    @ERQK_HLRB = obj['ERQK_HLRB']
                    @ERQK_HLRP = obj['ERQK_HLRP']
                    @ERQK_HLRR = obj['ERQK_HLRR']
                    @ERQK_RISKR = obj['ERQK_RISKR']
                    @ERQK_RISKS = obj['ERQK_RISKS']
                    @ERQK_RISKV = obj['ERQK_RISKV']
                    @HAIL_AFREQ = obj['HAIL_AFREQ']
                    @HAIL_ALRA = obj['HAIL_ALRA']
                    @HAIL_ALRB = obj['HAIL_ALRB']
                    @HAIL_ALRP = obj['HAIL_ALRP']
                    @HAIL_ALR_NPCTL = obj['HAIL_ALR_NPCTL']
                    @HAIL_EALA = obj['HAIL_EALA']
                    @HAIL_EALB = obj['HAIL_EALB']
                    @HAIL_EALP = obj['HAIL_EALP']
                    @HAIL_EALPE = obj['HAIL_EALPE']
                    @HAIL_EALR = obj['HAIL_EALR']
                    @HAIL_EALS = obj['HAIL_EALS']
                    @HAIL_EALT = obj['HAIL_EALT']
                    @HAIL_EVNTS = obj['HAIL_EVNTS']
                    @HAIL_EXPA = obj['HAIL_EXPA']
                    @HAIL_EXPB = obj['HAIL_EXPB']
                    @HAIL_EXPP = obj['HAIL_EXPP']
                    @HAIL_EXPPE = obj['HAIL_EXPPE']
                    @HAIL_EXPT = obj['HAIL_EXPT']
                    @HAIL_EXP_AREA = obj['HAIL_EXP_AREA']
                    @HAIL_HLRA = obj['HAIL_HLRA']
                    @HAIL_HLRB = obj['HAIL_HLRB']
                    @HAIL_HLRP = obj['HAIL_HLRP']
                    @HAIL_HLRR = obj['HAIL_HLRR']
                    @HAIL_RISKR = obj['HAIL_RISKR']
                    @HAIL_RISKS = obj['HAIL_RISKS']
                    @HAIL_RISKV = obj['HAIL_RISKV']
                    @HRCN_AFREQ = obj['HRCN_AFREQ']
                    @HRCN_ALRA = obj['HRCN_ALRA']
                    @HRCN_ALRB = obj['HRCN_ALRB']
                    @HRCN_ALRP = obj['HRCN_ALRP']
                    @HRCN_ALR_NPCTL = obj['HRCN_ALR_NPCTL']
                    @HRCN_EALA = obj['HRCN_EALA']
                    @HRCN_EALB = obj['HRCN_EALB']
                    @HRCN_EALP = obj['HRCN_EALP']
                    @HRCN_EALPE = obj['HRCN_EALPE']
                    @HRCN_EALR = obj['HRCN_EALR']
                    @HRCN_EALS = obj['HRCN_EALS']
                    @HRCN_EALT = obj['HRCN_EALT']
                    @HRCN_EVNTS = obj['HRCN_EVNTS']
                    @HRCN_EXPA = obj['HRCN_EXPA']
                    @HRCN_EXPB = obj['HRCN_EXPB']
                    @HRCN_EXPP = obj['HRCN_EXPP']
                    @HRCN_EXPPE = obj['HRCN_EXPPE']
                    @HRCN_EXPT = obj['HRCN_EXPT']
                    @HRCN_EXP_AREA = obj['HRCN_EXP_AREA']
                    @HRCN_HLRA = obj['HRCN_HLRA']
                    @HRCN_HLRB = obj['HRCN_HLRB']
                    @HRCN_HLRP = obj['HRCN_HLRP']
                    @HRCN_HLRR = obj['HRCN_HLRR']
                    @HRCN_RISKR = obj['HRCN_RISKR']
                    @HRCN_RISKS = obj['HRCN_RISKS']
                    @HRCN_RISKV = obj['HRCN_RISKV']
                    @HWAV_AFREQ = obj['HWAV_AFREQ']
                    @HWAV_ALRA = obj['HWAV_ALRA']
                    @HWAV_ALRB = obj['HWAV_ALRB']
                    @HWAV_ALRP = obj['HWAV_ALRP']
                    @HWAV_ALR_NPCTL = obj['HWAV_ALR_NPCTL']
                    @HWAV_EALA = obj['HWAV_EALA']
                    @HWAV_EALB = obj['HWAV_EALB']
                    @HWAV_EALP = obj['HWAV_EALP']
                    @HWAV_EALPE = obj['HWAV_EALPE']
                    @HWAV_EALR = obj['HWAV_EALR']
                    @HWAV_EALS = obj['HWAV_EALS']
                    @HWAV_EALT = obj['HWAV_EALT']
                    @HWAV_EVNTS = obj['HWAV_EVNTS']
                    @HWAV_EXPA = obj['HWAV_EXPA']
                    @HWAV_EXPB = obj['HWAV_EXPB']
                    @HWAV_EXPP = obj['HWAV_EXPP']
                    @HWAV_EXPPE = obj['HWAV_EXPPE']
                    @HWAV_EXPT = obj['HWAV_EXPT']
                    @HWAV_EXP_AREA = obj['HWAV_EXP_AREA']
                    @HWAV_HLRA = obj['HWAV_HLRA']
                    @HWAV_HLRB = obj['HWAV_HLRB']
                    @HWAV_HLRP = obj['HWAV_HLRP']
                    @HWAV_HLRR = obj['HWAV_HLRR']
                    @HWAV_RISKR = obj['HWAV_RISKR']
                    @HWAV_RISKS = obj['HWAV_RISKS']
                    @HWAV_RISKV = obj['HWAV_RISKV']
                    @ISTM_AFREQ = obj['ISTM_AFREQ']
                    @ISTM_ALRB = obj['ISTM_ALRB']
                    @ISTM_ALRP = obj['ISTM_ALRP']
                    @ISTM_ALR_NPCTL = obj['ISTM_ALR_NPCTL']
                    @ISTM_EALB = obj['ISTM_EALB']
                    @ISTM_EALP = obj['ISTM_EALP']
                    @ISTM_EALPE = obj['ISTM_EALPE']
                    @ISTM_EALR = obj['ISTM_EALR']
                    @ISTM_EALS = obj['ISTM_EALS']
                    @ISTM_EALT = obj['ISTM_EALT']
                    @ISTM_EVNTS = obj['ISTM_EVNTS']
                    @ISTM_EXPB = obj['ISTM_EXPB']
                    @ISTM_EXPP = obj['ISTM_EXPP']
                    @ISTM_EXPPE = obj['ISTM_EXPPE']
                    @ISTM_EXPT = obj['ISTM_EXPT']
                    @ISTM_EXP_AREA = obj['ISTM_EXP_AREA']
                    @ISTM_HLRB = obj['ISTM_HLRB']
                    @ISTM_HLRP = obj['ISTM_HLRP']
                    @ISTM_HLRR = obj['ISTM_HLRR']
                    @ISTM_RISKR = obj['ISTM_RISKR']
                    @ISTM_RISKS = obj['ISTM_RISKS']
                    @ISTM_RISKV = obj['ISTM_RISKV']
                    @LNDS_AFREQ = obj['LNDS_AFREQ']
                    @LNDS_ALRB = obj['LNDS_ALRB']
                    @LNDS_ALRP = obj['LNDS_ALRP']
                    @LNDS_ALR_NPCTL = obj['LNDS_ALR_NPCTL']
                    @LNDS_EALB = obj['LNDS_EALB']
                    @LNDS_EALP = obj['LNDS_EALP']
                    @LNDS_EALPE = obj['LNDS_EALPE']
                    @LNDS_EALR = obj['LNDS_EALR']
                    @LNDS_EALS = obj['LNDS_EALS']
                    @LNDS_EALT = obj['LNDS_EALT']
                    @LNDS_EVNTS = obj['LNDS_EVNTS']
                    @LNDS_EXPB = obj['LNDS_EXPB']
                    @LNDS_EXPP = obj['LNDS_EXPP']
                    @LNDS_EXPPE = obj['LNDS_EXPPE']
                    @LNDS_EXPT = obj['LNDS_EXPT']
                    @LNDS_EXP_AREA = obj['LNDS_EXP_AREA']
                    @LNDS_HLRB = obj['LNDS_HLRB']
                    @LNDS_HLRP = obj['LNDS_HLRP']
                    @LNDS_HLRR = obj['LNDS_HLRR']
                    @LNDS_RISKR = obj['LNDS_RISKR']
                    @LNDS_RISKS = obj['LNDS_RISKS']
                    @LNDS_RISKV = obj['LNDS_RISKV']
                    @LTNG_AFREQ = obj['LTNG_AFREQ']
                    @LTNG_ALRB = obj['LTNG_ALRB']
                    @LTNG_ALRP = obj['LTNG_ALRP']
                    @LTNG_ALR_NPCTL = obj['LTNG_ALR_NPCTL']
                    @LTNG_EALB = obj['LTNG_EALB']
                    @LTNG_EALP = obj['LTNG_EALP']
                    @LTNG_EALPE = obj['LTNG_EALPE']
                    @LTNG_EALR = obj['LTNG_EALR']
                    @LTNG_EALS = obj['LTNG_EALS']
                    @LTNG_EALT = obj['LTNG_EALT']
                    @LTNG_EVNTS = obj['LTNG_EVNTS']
                    @LTNG_EXPB = obj['LTNG_EXPB']
                    @LTNG_EXPP = obj['LTNG_EXPP']
                    @LTNG_EXPPE = obj['LTNG_EXPPE']
                    @LTNG_EXPT = obj['LTNG_EXPT']
                    @LTNG_EXP_AREA = obj['LTNG_EXP_AREA']
                    @LTNG_HLRB = obj['LTNG_HLRB']
                    @LTNG_HLRP = obj['LTNG_HLRP']
                    @LTNG_HLRR = obj['LTNG_HLRR']
                    @LTNG_RISKR = obj['LTNG_RISKR']
                    @LTNG_RISKS = obj['LTNG_RISKS']
                    @LTNG_RISKV = obj['LTNG_RISKV']
                    @NRI_VER = obj['NRI_VER']
                    @POPULATION = obj['POPULATION']
                    @RESL_RATNG = obj['RESL_RATNG']
                    @RESL_SCORE = obj['RESL_SCORE']
                    @RESL_SPCTL = obj['RESL_SPCTL']
                    @RESL_VALUE = obj['RESL_VALUE']
                    @RFLD_AFREQ = obj['RFLD_AFREQ']
                    @RFLD_ALRA = obj['RFLD_ALRA']
                    @RFLD_ALRB = obj['RFLD_ALRB']
                    @RFLD_ALRP = obj['RFLD_ALRP']
                    @RFLD_ALR_NPCTL = obj['RFLD_ALR_NPCTL']
                    @RFLD_EALA = obj['RFLD_EALA']
                    @RFLD_EALB = obj['RFLD_EALB']
                    @RFLD_EALP = obj['RFLD_EALP']
                    @RFLD_EALPE = obj['RFLD_EALPE']
                    @RFLD_EALR = obj['RFLD_EALR']
                    @RFLD_EALS = obj['RFLD_EALS']
                    @RFLD_EALT = obj['RFLD_EALT']
                    @RFLD_EVNTS = obj['RFLD_EVNTS']
                    @RFLD_EXPA = obj['RFLD_EXPA']
                    @RFLD_EXPB = obj['RFLD_EXPB']
                    @RFLD_EXPP = obj['RFLD_EXPP']
                    @RFLD_EXPPE = obj['RFLD_EXPPE']
                    @RFLD_EXPT = obj['RFLD_EXPT']
                    @RFLD_EXP_AREA = obj['RFLD_EXP_AREA']
                    @RFLD_HLRA = obj['RFLD_HLRA']
                    @RFLD_HLRB = obj['RFLD_HLRB']
                    @RFLD_HLRP = obj['RFLD_HLRP']
                    @RFLD_HLRR = obj['RFLD_HLRR']
                    @RFLD_RISKR = obj['RFLD_RISKR']
                    @RFLD_RISKS = obj['RFLD_RISKS']
                    @RFLD_RISKV = obj['RFLD_RISKV']
                    @RISK_RATNG = obj['RISK_RATNG']
                    @RISK_SCORE = obj['RISK_SCORE']
                    @RISK_SPCTL = obj['RISK_SPCTL']
                    @RISK_VALUE = obj['RISK_VALUE']
                    @SOVI_RATNG = obj['SOVI_RATNG']
                    @SOVI_SCORE = obj['SOVI_SCORE']
                    @SOVI_SPCTL = obj['SOVI_SPCTL']
                    @STATE = obj['STATE']
                    @STATEABBRV = obj['STATEABBRV']
                    @STATEFIPS = obj['STATEFIPS']
                    @STCOFIPS = obj['STCOFIPS']
                    @SWND_AFREQ = obj['SWND_AFREQ']
                    @SWND_ALRA = obj['SWND_ALRA']
                    @SWND_ALRB = obj['SWND_ALRB']
                    @SWND_ALRP = obj['SWND_ALRP']
                    @SWND_ALR_NPCTL = obj['SWND_ALR_NPCTL']
                    @SWND_EALA = obj['SWND_EALA']
                    @SWND_EALB = obj['SWND_EALB']
                    @SWND_EALP = obj['SWND_EALP']
                    @SWND_EALPE = obj['SWND_EALPE']
                    @SWND_EALR = obj['SWND_EALR']
                    @SWND_EALS = obj['SWND_EALS']
                    @SWND_EALT = obj['SWND_EALT']
                    @SWND_EVNTS = obj['SWND_EVNTS']
                    @SWND_EXPA = obj['SWND_EXPA']
                    @SWND_EXPB = obj['SWND_EXPB']
                    @SWND_EXPP = obj['SWND_EXPP']
                    @SWND_EXPPE = obj['SWND_EXPPE']
                    @SWND_EXPT = obj['SWND_EXPT']
                    @SWND_EXP_AREA = obj['SWND_EXP_AREA']
                    @SWND_HLRA = obj['SWND_HLRA']
                    @SWND_HLRB = obj['SWND_HLRB']
                    @SWND_HLRP = obj['SWND_HLRP']
                    @SWND_HLRR = obj['SWND_HLRR']
                    @SWND_RISKR = obj['SWND_RISKR']
                    @SWND_RISKS = obj['SWND_RISKS']
                    @SWND_RISKV = obj['SWND_RISKV']
                    @TRACT = obj['TRACT']
                    @TRACTFIPS = obj['TRACTFIPS']
                    @TRND_AFREQ = obj['TRND_AFREQ']
                    @TRND_ALRA = obj['TRND_ALRA']
                    @TRND_ALRB = obj['TRND_ALRB']
                    @TRND_ALRP = obj['TRND_ALRP']
                    @TRND_ALR_NPCTL = obj['TRND_ALR_NPCTL']
                    @TRND_EALA = obj['TRND_EALA']
                    @TRND_EALB = obj['TRND_EALB']
                    @TRND_EALP = obj['TRND_EALP']
                    @TRND_EALPE = obj['TRND_EALPE']
                    @TRND_EALR = obj['TRND_EALR']
                    @TRND_EALS = obj['TRND_EALS']
                    @TRND_EALT = obj['TRND_EALT']
                    @TRND_EVNTS = obj['TRND_EVNTS']
                    @TRND_EXPA = obj['TRND_EXPA']
                    @TRND_EXPB = obj['TRND_EXPB']
                    @TRND_EXPP = obj['TRND_EXPP']
                    @TRND_EXPPE = obj['TRND_EXPPE']
                    @TRND_EXPT = obj['TRND_EXPT']
                    @TRND_EXP_AREA = obj['TRND_EXP_AREA']
                    @TRND_HLRA = obj['TRND_HLRA']
                    @TRND_HLRB = obj['TRND_HLRB']
                    @TRND_HLRP = obj['TRND_HLRP']
                    @TRND_HLRR = obj['TRND_HLRR']
                    @TRND_RISKR = obj['TRND_RISKR']
                    @TRND_RISKS = obj['TRND_RISKS']
                    @TRND_RISKV = obj['TRND_RISKV']
                    @TSUN_AFREQ = obj['TSUN_AFREQ']
                    @TSUN_ALRB = obj['TSUN_ALRB']
                    @TSUN_ALRP = obj['TSUN_ALRP']
                    @TSUN_ALR_NPCTL = obj['TSUN_ALR_NPCTL']
                    @TSUN_EALB = obj['TSUN_EALB']
                    @TSUN_EALP = obj['TSUN_EALP']
                    @TSUN_EALPE = obj['TSUN_EALPE']
                    @TSUN_EALR = obj['TSUN_EALR']
                    @TSUN_EALS = obj['TSUN_EALS']
                    @TSUN_EALT = obj['TSUN_EALT']
                    @TSUN_EVNTS = obj['TSUN_EVNTS']
                    @TSUN_EXPB = obj['TSUN_EXPB']
                    @TSUN_EXPP = obj['TSUN_EXPP']
                    @TSUN_EXPPE = obj['TSUN_EXPPE']
                    @TSUN_EXPT = obj['TSUN_EXPT']
                    @TSUN_EXP_AREA = obj['TSUN_EXP_AREA']
                    @TSUN_HLRB = obj['TSUN_HLRB']
                    @TSUN_HLRP = obj['TSUN_HLRP']
                    @TSUN_HLRR = obj['TSUN_HLRR']
                    @TSUN_RISKR = obj['TSUN_RISKR']
                    @TSUN_RISKS = obj['TSUN_RISKS']
                    @TSUN_RISKV = obj['TSUN_RISKV']
                    @VLCN_AFREQ = obj['VLCN_AFREQ']
                    @VLCN_ALRB = obj['VLCN_ALRB']
                    @VLCN_ALRP = obj['VLCN_ALRP']
                    @VLCN_ALR_NPCTL = obj['VLCN_ALR_NPCTL']
                    @VLCN_EALB = obj['VLCN_EALB']
                    @VLCN_EALP = obj['VLCN_EALP']
                    @VLCN_EALPE = obj['VLCN_EALPE']
                    @VLCN_EALR = obj['VLCN_EALR']
                    @VLCN_EALS = obj['VLCN_EALS']
                    @VLCN_EALT = obj['VLCN_EALT']
                    @VLCN_EVNTS = obj['VLCN_EVNTS']
                    @VLCN_EXPB = obj['VLCN_EXPB']
                    @VLCN_EXPP = obj['VLCN_EXPP']
                    @VLCN_EXPPE = obj['VLCN_EXPPE']
                    @VLCN_EXPT = obj['VLCN_EXPT']
                    @VLCN_EXP_AREA = obj['VLCN_EXP_AREA']
                    @VLCN_HLRB = obj['VLCN_HLRB']
                    @VLCN_HLRP = obj['VLCN_HLRP']
                    @VLCN_HLRR = obj['VLCN_HLRR']
                    @VLCN_RISKR = obj['VLCN_RISKR']
                    @VLCN_RISKS = obj['VLCN_RISKS']
                    @VLCN_RISKV = obj['VLCN_RISKV']
                    @WFIR_AFREQ = obj['WFIR_AFREQ']
                    @WFIR_ALRA = obj['WFIR_ALRA']
                    @WFIR_ALRB = obj['WFIR_ALRB']
                    @WFIR_ALRP = obj['WFIR_ALRP']
                    @WFIR_ALR_NPCTL = obj['WFIR_ALR_NPCTL']
                    @WFIR_EALA = obj['WFIR_EALA']
                    @WFIR_EALB = obj['WFIR_EALB']
                    @WFIR_EALP = obj['WFIR_EALP']
                    @WFIR_EALPE = obj['WFIR_EALPE']
                    @WFIR_EALR = obj['WFIR_EALR']
                    @WFIR_EALS = obj['WFIR_EALS']
                    @WFIR_EALT = obj['WFIR_EALT']
                    @WFIR_EVNTS = obj['WFIR_EVNTS']
                    @WFIR_EXPA = obj['WFIR_EXPA']
                    @WFIR_EXPB = obj['WFIR_EXPB']
                    @WFIR_EXPP = obj['WFIR_EXPP']
                    @WFIR_EXPPE = obj['WFIR_EXPPE']
                    @WFIR_EXPT = obj['WFIR_EXPT']
                    @WFIR_EXP_AREA = obj['WFIR_EXP_AREA']
                    @WFIR_HLRA = obj['WFIR_HLRA']
                    @WFIR_HLRB = obj['WFIR_HLRB']
                    @WFIR_HLRP = obj['WFIR_HLRP']
                    @WFIR_HLRR = obj['WFIR_HLRR']
                    @WFIR_RISKR = obj['WFIR_RISKR']
                    @WFIR_RISKS = obj['WFIR_RISKS']
                    @WFIR_RISKV = obj['WFIR_RISKV']
                    @WNTW_AFREQ = obj['WNTW_AFREQ']
                    @WNTW_ALRA = obj['WNTW_ALRA']
                    @WNTW_ALRB = obj['WNTW_ALRB']
                    @WNTW_ALRP = obj['WNTW_ALRP']
                    @WNTW_ALR_NPCTL = obj['WNTW_ALR_NPCTL']
                    @WNTW_EALA = obj['WNTW_EALA']
                    @WNTW_EALB = obj['WNTW_EALB']
                    @WNTW_EALP = obj['WNTW_EALP']
                    @WNTW_EALPE = obj['WNTW_EALPE']
                    @WNTW_EALR = obj['WNTW_EALR']
                    @WNTW_EALS = obj['WNTW_EALS']
                    @WNTW_EALT = obj['WNTW_EALT']
                    @WNTW_EVNTS = obj['WNTW_EVNTS']
                    @WNTW_EXPA = obj['WNTW_EXPA']
                    @WNTW_EXPB = obj['WNTW_EXPB']
                    @WNTW_EXPP = obj['WNTW_EXPP']
                    @WNTW_EXPPE = obj['WNTW_EXPPE']
                    @WNTW_EXPT = obj['WNTW_EXPT']
                    @WNTW_EXP_AREA = obj['WNTW_EXP_AREA']
                    @WNTW_HLRA = obj['WNTW_HLRA']
                    @WNTW_HLRB = obj['WNTW_HLRB']
                    @WNTW_HLRP = obj['WNTW_HLRP']
                    @WNTW_HLRR = obj['WNTW_HLRR']
                    @WNTW_RISKR = obj['WNTW_RISKR']
                    @WNTW_RISKS = obj['WNTW_RISKS']
                    @WNTW_RISKV = obj['WNTW_RISKV']
                end
            end
        end
    end
end